server:
  port: 8202

spring:
  application:
    name: readme

  datasource:
    url: jdbc:postgresql://localhost:5420/readme
    username: postgres
    password: 1004

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  secret: bookstoreSecretKey2026ProjectPortfolio
  expiration: 3600000

file:
  upload-dir: /uploads/